name: app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_icons: ^1.1.0
  flutter_bloc: ^4.0.1
  equatable: ^1.2.0
  firebase_auth: ^0.16.1
  cloud_firestore: ^0.13.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  bloc_test: ^5.1.0

flutter:
  uses-material-design: true
