name: CD_Android
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1.3.2
        with:
          flutter-version: '1.17.4'

      # Get flutter dependencies.
      - run: flutter pub get

      # Check for any formatting issues in the code.
      - run: flutter format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .

      # Run widget tests for our flutter project.
      - run: flutter test

      # Build apk.
      - run: flutter build apk --flavor dev
        # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@master
        with:
          name: apk-release
          path: build/app/outputs/apk/dev/release/app-dev-release.apk

      - name: Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.2.2
        with:
          appId: ${{secrets.FIREBASE_APP_ID_ANDROID_DEV}}
          token: ${{secrets.FIREBASE_TOKEN_DEV}}
          groups: android
          file: build/app/outputs/apk/dev/release/app-dev-release.apk
