name: CD_iOS

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action
        with:
          channel: 'stable'
      - name: Flutter setup
        run: |
          flutter pub get
          flutter build ios --release --no-codesign --flavor dev
      - name: Build
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          MATCH_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
        run: |
          cd ios
          fastlane build
      # - name: Use Node.js 10.x
      #   uses: actions/setup-node@v1
      #   with:
      #     node-version: 10.x
      # - name: Install Firebase
      #   run: yarn install
      # - name: Upload ipa
      #   run: yarn run firebase appdistribution:distribute ios/build/Runner.ipa --app "${{ secrets.IOS_APP_ID }}" --token "${{ secrets.FIREBASE_TOKEN }}"
      - name: Distribute dev App through Firebase App Distributions
        if: success()
        uses: wzieba/Firebase-Distribution-Github-Action
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: ios
          file: build/app/outputs/apk/release/app-dev-release.apk
