name: CD_iOS

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1.3.2
        with:
          flutter-version: '1.17.4'
      # Get flutter dependencies.
      - run: flutter pub get

      # Check for any formatting issues in the code.
      - run: flutter format --set-exit-if-changed .

      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .

      # Build ios app
      - run: flutter build ios --release --no-codesign --flavor dev

      - name: Build
        env:
          PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          MATCH_PASSWORD: ${{ secrets.IOS_CERTIFICATE_PASSWORD }}
        run: |
          cd ios
          fastlane build

      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Install Firebase
        run: npm install firebase-tools -g
      - run: pwd
      - name: Upload ipa
        run: firebase appdistribution:distribute ios/build/Runner.ipa --app "${{ secrets.FIREBASE_APP_ID_IOS_DEV }}" --token "${{ secrets.FIREBASE_TOKEN_DEV }}" --groups ios
